# Generated by Django 5.2.8 on 2025-12-03 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaddata',
            name='source',
            field=models.CharField(default='', max_length=255),
        ),
    ]
